### PR TITLE
Hach internship no longer available

### PR DESCRIPTION
**Pull request by ramjayakumar21**

### CODE REVIEW

**Comment by kanjurer** [comment]
I think this PR is duplicate https://github.com/jenndryden/Canadian-Tech-Internships-Summer-2024/pull/125 👅

**Review by kanjurer — CHANGES_REQUESTED** [review]
https://github.com/jenndryden/Canadian-Tech-Internships-Summer-2024/pull/125

**Comment by ramjayakumar21** [comment]
Oh yeah it is, my bad didn’t see it

**Comment by jenndryden** [comment]
thank you so much for adding this anyways, appreciate it! :) welcome! 🎉

**Pull request closed without merging**
