### PR TITLE
Capital One

### PR DESCRIPTION
**Pull request by kanjurer**

### CODE REVIEW

**Comment by ShevinuM** [comment]
Hey, was this a recent posting you saw? Saw that on LinkedIn it says no longer accepting applications so wondering if the LinkedIn one was an older one and this is a newer one. [LinkedIn Posting](https://www.linkedin.com/jobs/view/business-analyst-intern-summer-2024-at-capital-one-3668407007/)

**Comment by kanjurer** [comment]
Oh? That is odd lol. I think they reposted https://www.linkedin.com/jobs/view/3699668631/?refId=ec467159-5631-403a-bdaa-2ece2fd43d11&trackingId=8Fb9OFwxT8qzZ9mOPxslQA%3D%3D

**Comment by ShevinuM** [comment]
> Oh? That is odd lol. I think they reposted https://www.linkedin.com/jobs/view/3699668631/?refId=ec467159-5631-403a-bdaa-2ece2fd43d11&trackingId=8Fb9OFwxT8qzZ9mOPxslQA%3D%3D

Haha cool. These companies are making everything confusing lol.

**Comment by kanjurer** [comment]
> > Oh? That is odd lol. I think they reposted https://www.linkedin.com/jobs/view/3699668631/?refId=ec467159-5631-403a-bdaa-2ece2fd43d11&trackingId=8Fb9OFwxT8qzZ9mOPxslQA%3D%3D
> 
> Haha cool. These companies are making everything confusing lol.

Istg, Imma cry 😭

**Pull request closed without merging**
